[project]
name = "cicada"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fake-rpi>=0.7.1",
    "paho-mqtt>=2.1.0",
]
