[project]
name = "cicada"
version = "0.3.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fake-rpi>=0.7.1",
    "mfrc522-python>=0.0.7",
    "paho-mqtt>=2.1.0",
]
